export const events = [
  {
    id: "EVT-10041",
    orderNumber: "C-24018",
    eventName: "Board of Trustees Breakfast",
    eventType: "Meeting",
    serviceType: "Buffet",
    date: "2026-07-07",
    startTime: "07:30",
    endTime: "09:00",
    loadTime: "06:45",
    deliveryTime: "07:10",
    guestCount: 42,
    coordinator: "Elena Brooks",
    lifecycleStatus: "Confirmed",
    productionStatus: "Prep",
    setupStatus: "Needs review",
    deliveryStatus: "Scheduled",
    readiness: "Attention",
    readinessSummary:
      "Dietary counts changed after pastry quantities were locked. Confirm gluten-free items before packing.",
    customer: {
      name: "President's Office",
      contact: "Maya Patel",
      phone: "555-0142",
      email: "maya.patel@campus.edu",
    },
    location: {
      building: "Admin Hall",
      room: "Trustees Room",
      address: "100 College Ave",
      accessNotes: "Use east service elevator. Security opens service corridor at 6:30.",
    },
    menu: [
      "Coffee and tea service",
      "Mini quiche",
      "Fruit platters",
      "Assorted pastries",
      "Sparkling water",
    ],
    dietary: ["4 gluten-free", "2 vegan", "1 nut allergy"],
    equipment: ["2 coffee cambros", "8 chafers", "Black linen", "Compostable plates"],
    staffing: ["Lead: Marcus", "Server: Ana", "Driver: Nia"],
    setupNotes: "U-shape table remains from prior evening. Buffet on north credenza. Coffee by entry.",
    deliveryNotes: "Load cold fruit last. Deliver pastries in labeled allergen-safe tray.",
    internalNotes: "Client is sensitive to late coffee. Confirm cambros are full before departure.",
    aiSummary:
      "Breakfast is mostly ready, but dietary counts changed after production locked pastry quantities.",
  },
  {
    id: "EVT-10042",
    orderNumber: "C-24021",
    eventName: "Admissions Counselor Lunch",
    eventType: "Campus Event",
    serviceType: "Drop-off",
    date: "2026-07-07",
    startTime: "11:45",
    endTime: "13:00",
    loadTime: "11:05",
    deliveryTime: "11:25",
    guestCount: 28,
    coordinator: "Ruth Kim",
    lifecycleStatus: "Confirmed",
    productionStatus: "Ready",
    setupStatus: "Ready",
    deliveryStatus: "Scheduled",
    readiness: "Ready",
    readinessSummary: "Ready for delivery. No open review items.",
    customer: {
      name: "Admissions",
      contact: "Jon Reyes",
      phone: "555-0198",
      email: "jon.reyes@campus.edu",
    },
    location: {
      building: "Welcome Center",
      room: "Room 204",
      address: "12 College Way",
      accessNotes: "Front desk has cart key. Avoid lobby stairs.",
    },
    menu: ["Boxed turkey sandwiches", "Vegetarian wraps", "Kettle chips", "Cookies", "Iced tea"],
    dietary: ["6 vegetarian", "3 dairy-free"],
    equipment: ["Disposable platters", "Drink tub", "Ice scoop"],
    staffing: ["Driver: Leo"],
    setupNotes: "Drop on rear service table. Client handles room reset.",
    deliveryNotes: "Call Jon on arrival. Leave tea in drink tub with ice.",
    internalNotes: "Pack extra napkins; this group usually requests more.",
    aiSummary: "Lunch is ready and has no unresolved operational blockers.",
  },
  {
    id: "EVT-10043",
    orderNumber: "C-24029",
    eventName: "Chemistry Poster Reception",
    eventType: "Reception",
    serviceType: "Stations",
    date: "2026-07-07",
    startTime: "16:30",
    endTime: "18:00",
    loadTime: "15:30",
    deliveryTime: "15:55",
    guestCount: 120,
    coordinator: "Elena Brooks",
    lifecycleStatus: "Confirmed",
    productionStatus: "In progress",
    setupStatus: "Needs review",
    deliveryStatus: "Scheduled",
    readiness: "At risk",
    readinessSummary:
      "Guest count increased by 30 and the room layout does not show enough station space.",
    customer: {
      name: "Chemistry Department",
      contact: "Dr. Howard Lee",
      phone: "555-0177",
      email: "howard.lee@campus.edu",
    },
    location: {
      building: "Science Pavilion",
      room: "Atrium",
      address: "90 Lab Road",
      accessNotes: "Use loading dock B. Freight elevator reservation starts at 15:20.",
    },
    menu: [
      "Cheese boards",
      "Vegetable crudite",
      "Chicken skewers",
      "Mini desserts",
      "Still and sparkling water",
    ],
    dietary: ["12 vegetarian", "5 gluten-free", "2 vegan"],
    equipment: ["6 six-foot tables", "Station risers", "Black linen", "Trash and compost trio"],
    staffing: ["Lead: Simone", "Server: Priya", "Server: Matias", "Driver: Nia"],
    setupNotes: "Poster boards will be installed by 14:00. Keep food stations away from main poster aisle.",
    deliveryNotes: "Hot skewers leave kitchen at 16:05. Stage cold boards first.",
    internalNotes: "Department chair requested extra water near west entrance.",
    aiSummary:
      "Reception needs human review because count and room layout changed after the production plan was started.",
  },
  {
    id: "EVT-10044",
    orderNumber: "C-24033",
    eventName: "Alumni Dinner Setup",
    eventType: "Dinner",
    serviceType: "Plated",
    date: "2026-07-07",
    startTime: "18:30",
    endTime: "21:30",
    loadTime: "16:45",
    deliveryTime: "17:15",
    guestCount: 86,
    coordinator: "Marcus Hale",
    lifecycleStatus: "Tentative",
    productionStatus: "Prep",
    setupStatus: "Blocked",
    deliveryStatus: "Unscheduled",
    readiness: "At risk",
    readinessSummary:
      "Final room diagram and entree counts are still missing. Delivery cannot be confirmed.",
    customer: {
      name: "Alumni Relations",
      contact: "Paula Grant",
      phone: "555-0129",
      email: "paula.grant@campus.edu",
    },
    location: {
      building: "Founders Hall",
      room: "Ballroom",
      address: "8 Old Main Drive",
      accessNotes: "Dock shared with rental company. Confirm load-in sequence.",
    },
    menu: ["Seasonal salad", "Herb chicken", "Mushroom risotto", "Roasted vegetables", "Chocolate torte"],
    dietary: ["Counts pending", "Known: 4 vegan", "Known: 3 gluten-free"],
    equipment: ["Round tables pending diagram", "Ivory linen", "China and flatware", "Coffee station"],
    staffing: ["Lead: Tessa", "Servers pending final count"],
    setupNotes: "Awaiting diagram from Events Office. Rental company arrives at 15:00.",
    deliveryNotes: "Delivery window cannot be finalized until dock sequence is confirmed.",
    internalNotes: "High-visibility dinner. Do not release final prep sheet without entree counts.",
    aiSummary:
      "Dinner should stay in review until final entree counts, room diagram, and dock timing are confirmed.",
  },
  {
    id: "EVT-10045",
    orderNumber: "C-24035",
    eventName: "Library Donor Coffee",
    eventType: "Reception",
    serviceType: "Coffee break",
    date: "2026-07-08",
    startTime: "10:00",
    endTime: "11:00",
    loadTime: "09:15",
    deliveryTime: "09:35",
    guestCount: 35,
    coordinator: "Ruth Kim",
    lifecycleStatus: "Confirmed",
    productionStatus: "Not started",
    setupStatus: "Ready",
    deliveryStatus: "Scheduled",
    readiness: "Attention",
    readinessSummary:
      "Tomorrow's coffee service is missing a pickup owner for cleanup.",
    customer: {
      name: "Library Advancement",
      contact: "Nina Carver",
      phone: "555-0110",
      email: "nina.carver@campus.edu",
    },
    location: {
      building: "Main Library",
      room: "Special Collections",
      address: "17 Scholar Lane",
      accessNotes: "No open liquids inside archive room. Service table stays in foyer.",
    },
    menu: ["Coffee service", "Tea service", "Scones", "Lemon bars", "Fruit skewers"],
    dietary: ["2 vegan", "Nut-free pastry tray requested"],
    equipment: ["1 coffee cambro", "1 hot water cambro", "White linen", "Small compost bin"],
    staffing: ["Driver: Leo"],
    setupNotes: "Foyer only. Keep archive doors clear.",
    deliveryNotes: "Use small cart. Library elevator is narrow.",
    internalNotes: "Pickup owner has not been assigned.",
    aiSummary: "Coffee service is simple but still needs a cleanup owner.",
  },
];

export const checklistItems = [
  {
    id: "TASK-001",
    eventId: "EVT-10041",
    phase: "Kitchen prep",
    title: "Confirm gluten-free pastry count with bakery",
    ownerRole: "Kitchen lead",
    dueTime: "06:20",
    status: "Todo",
    source: "ai",
    approvalState: "pending_review",
    suggestedBecause: "Dietary count changed after pastry production was locked.",
  },
  {
    id: "TASK-002",
    eventId: "EVT-10041",
    phase: "Packing",
    title: "Label allergen-safe pastry tray",
    ownerRole: "Packing",
    dueTime: "06:35",
    status: "Todo",
    source: "human",
    approvalState: "approved",
  },
  {
    id: "TASK-003",
    eventId: "EVT-10042",
    phase: "Delivery",
    title: "Call Jon Reyes on arrival",
    ownerRole: "Driver",
    dueTime: "11:20",
    status: "Todo",
    source: "human",
    approvalState: "approved",
  },
  {
    id: "TASK-004",
    eventId: "EVT-10043",
    phase: "Kitchen prep",
    title: "Scale chicken skewers for updated guest count",
    ownerRole: "Kitchen lead",
    dueTime: "14:30",
    status: "In progress",
    source: "ai",
    approvalState: "approved",
    suggestedBecause: "Guest count increased from 90 to 120.",
  },
  {
    id: "TASK-005",
    eventId: "EVT-10043",
    phase: "Setup",
    title: "Verify station layout with poster board placement",
    ownerRole: "Setup lead",
    dueTime: "15:00",
    status: "Todo",
    source: "ai",
    approvalState: "pending_review",
    suggestedBecause: "Room layout may not support six food stations after poster placement.",
  },
  {
    id: "TASK-006",
    eventId: "EVT-10044",
    phase: "Planning",
    title: "Request final entree counts from Paula Grant",
    ownerRole: "Coordinator",
    dueTime: "12:00",
    status: "Todo",
    source: "human",
    approvalState: "approved",
  },
  {
    id: "TASK-007",
    eventId: "EVT-10044",
    phase: "Setup",
    title: "Confirm dock sequence with rental company",
    ownerRole: "Setup lead",
    dueTime: "13:00",
    status: "Todo",
    source: "ai",
    approvalState: "pending_review",
    suggestedBecause: "Delivery status is unscheduled and dock access is shared.",
  },
  {
    id: "TASK-008",
    eventId: "EVT-10045",
    phase: "Cleanup",
    title: "Assign pickup owner for coffee service",
    ownerRole: "Coordinator",
    dueTime: "2026-07-08 09:00",
    status: "Todo",
    source: "ai",
    approvalState: "pending_review",
    suggestedBecause: "No cleanup owner is listed for a donor-facing event.",
  },
];

export const reviewItems = [
  {
    id: "REV-001",
    eventId: "EVT-10041",
    type: "Missing information",
    severity: "Medium",
    status: "Open",
    title: "Gluten-free pastry quantity needs confirmation",
    evidence: "Dietary changed from 2 to 4 gluten-free guests after pastry order lock.",
    impact: "Kitchen prep and packing labels may be wrong.",
    suggestedAction: "Approve the suggested task and call bakery before 06:20.",
    humanDecision: "",
  },
  {
    id: "REV-002",
    eventId: "EVT-10043",
    type: "Change impact",
    severity: "High",
    status: "Open",
    title: "Guest count increase affects production and station layout",
    evidence: "Guest count changed from 90 to 120 after production had started.",
    impact: "Chicken skewers, water, station spacing, and setup labor may be short.",
    suggestedAction: "Scale hot item quantities and verify station layout before 15:00.",
    humanDecision: "",
  },
  {
    id: "REV-003",
    eventId: "EVT-10044",
    type: "Risk",
    severity: "High",
    status: "Open",
    title: "Alumni dinner is tentative with missing final counts",
    evidence: "Lifecycle is tentative, entree counts are pending, and delivery is unscheduled.",
    impact: "Kitchen cannot finalize prep and setup cannot assign delivery sequence.",
    suggestedAction: "Keep in review until counts, diagram, and dock timing are confirmed.",
    humanDecision: "",
  },
  {
    id: "REV-004",
    eventId: "EVT-10045",
    type: "Suggested task",
    severity: "Low",
    status: "Open",
    title: "Cleanup owner missing for Library Donor Coffee",
    evidence: "No pickup or cleanup owner appears in staffing or notes.",
    impact: "Coffee equipment may be left in a public donor area.",
    suggestedAction: "Approve task to assign a pickup owner tomorrow morning.",
    humanDecision: "",
  },
];

export const changeLog = [
  {
    id: "CHG-001",
    eventId: "EVT-10041",
    timestamp: "2026-07-06 15:42",
    actor: "Maya Patel",
    source: "client",
    field: "Dietary",
    before: "2 gluten-free",
    after: "4 gluten-free",
  },
  {
    id: "CHG-002",
    eventId: "EVT-10043",
    timestamp: "2026-07-07 09:15",
    actor: "Dr. Howard Lee",
    source: "client",
    field: "Guest count",
    before: "90",
    after: "120",
  },
  {
    id: "CHG-003",
    eventId: "EVT-10044",
    timestamp: "2026-07-07 08:10",
    actor: "Events Office",
    source: "internal",
    field: "Room diagram",
    before: "Draft requested",
    after: "Still pending",
  },
  {
    id: "CHG-004",
    eventId: "EVT-10045",
    timestamp: "2026-07-06 16:05",
    actor: "Nina Carver",
    source: "client",
    field: "Location note",
    before: "Special Collections",
    after: "Service must stay in foyer",
  },
];

export const navItems = [
  { label: "Today", path: "/today" },
  { label: "Events", path: "/events" },
  { label: "Production", path: "/production" },
  { label: "Setup & Delivery", path: "/setup-delivery" },
  { label: "Tasks", path: "/tasks" },
  { label: "Review", path: "/review" },
  { label: "Handoff", path: "/handoff" },
];
