"""MacFleet security: fleet isolation, authentication, encryption, and validation."""

from macfleet.security.audit import audit_event, audit_log_path
from macfleet.security.auth import (
    MIN_TOKEN_LENGTH,
    TOKEN_FILE,
    AuthRateLimiter,
    GradientValidationError,
    SecurityConfig,
    compute_client_hello_proof,
    compute_response,
    create_client_ssl_context,
    create_server_ssl_context,
    create_server_tls_context,
    generate_challenge,
    generate_fleet_token,
    resolve_token,
    resolve_token_with_file,
    sign_heartbeat,
    sign_heartbeat_response,
    tls_channel_binding_from_writer,
    validate_gradient_metadata,
    validate_gradients,
    verify_client_hello_proof,
    verify_heartbeat,
    verify_heartbeat_response,
    verify_response,
)

__all__ = [
    "audit_event",
    "audit_log_path",
    "MIN_TOKEN_LENGTH",
    "TOKEN_FILE",
    "AuthRateLimiter",
    "GradientValidationError",
    "SecurityConfig",
    "compute_client_hello_proof",
    "compute_response",
    "create_client_ssl_context",
    "create_server_ssl_context",
    "create_server_tls_context",
    "generate_challenge",
    "generate_fleet_token",
    "resolve_token",
    "resolve_token_with_file",
    "sign_heartbeat",
    "sign_heartbeat_response",
    "tls_channel_binding_from_writer",
    "validate_gradient_metadata",
    "validate_gradients",
    "verify_client_hello_proof",
    "verify_heartbeat",
    "verify_heartbeat_response",
    "verify_response",
]
